version: '3.8'

services:
  api:
    build: .
    container_name: restaurant-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    env_file:
      - .env
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge